### ISSUE TITLE
Infografía

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Yabin-2021#1]
[Infografía dev smart contract.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Yabin-2021/files/8679840/Infografia.dev.smart.contract.pdf)

Anexo infografía

**Comment by bg55-a** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
